import {
  Home,
  PackageCheck,
  Truck,
  Building2,
  FileText,
  WalletMinimal,
  Package,
  Mountain,
  CreditCard,
  FileCheck2,
  Users,
  Shield,
  User,
  Banknote,
  Droplet,
  Fuel,
  Undo2,
  ClipboardList,
} from "lucide-react";

export const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export const ICONS = {
  dashboard: Home,
  orders: PackageCheck,
  truckOrders: Truck,
  cashTransactions: Banknote,
  returns: Undo2,
  waitingList: ClipboardList,
  companies: Building2,
  companyInvoices: FileText,
  mineInvoices: WalletMinimal,
  products: Package,
  dispensers: Droplet,
  tankers: Fuel,
  mines: Mountain,
  companyCredits: CreditCard,
  creditApproval: FileCheck2,
  staff: Users,
  roles: Shield,
  profile: User,
} as const;
