export const financialFormData = [
  {
    name: "supplierName",
    label: "Supplier Name",
    placeholder: "Enter supplier name",
    type: "text",
    required: true,
  },
  {
    name: "invoiceNumber",
    label: "Invoice Number",
    placeholder: "Enter invoice number",
    type: "text",
    required: true,
  },
  {
    name: "invoiceUnitPrice",
    label: "Invoice Unit Price (R)",
    type: "number",
    step: "0.01",
    min: "0.01",
    placeholder: "Enter price per litre",
    required: true,
  },
  {
    name: "gridAtPurchase",
    label: "Grid (R)",
    type: "number",
    step: "0.01",
    min: "0.01",
    placeholder: "Enter selling price per litre",
    required: true,
  },
  {
    name: "discount",
    label: "Discount Amount (R)",
    type: "number",
    step: "0.01",
    min: "0",
    placeholder: "Enter discount amount in Rands",
  },
  {
    name: "invoiceDate",
    label: "Invoice Date",
    type: "date",
    placeholder: "Select invoice date",
    required: true,
  },
];

export const quantityFormData = [
  {
    name: "quantityAdded",
    label: "Quantity Added (L)",
    placeholder: "Enter quantity added",
    type: "number",
    step: "0.1",
    min: "0.1",
    required: true,
  },
  {
    name: "actualMeterReading",
    label: "ATG Meter Reading (L)",
    placeholder: "Enter actual meter reading",
    type: "number",
    step: "0.1",
    min: "0",
    required: true,
  },
  {
    name: "manualDippingReading",
    label: "Manual Dipping Reading (L)",
    placeholder: "Enter manual dipping reading",
    type: "number",
    step: "0.1",
    min: "0",
    required: true,
  },
];
